export const BASE_URL = 'https://localhost:5050';  // Gateway's Adress
export const PRODUCT_URL = `${BASE_URL}/api/products`;
export const CART_URL = `${BASE_URL}/api/cart`;
export const FAVOURITES_URL = `${BASE_URL}/api/favourites`;
export const CART_GET_URL = `${BASE_URL}/api/cart/getcart`; 
export const CART_REMOVE_ITEM_URL = `${BASE_URL}/api/cart/removefromcart`; 
export const ORDER_URL = `${BASE_URL}/api/order`;
export const AUTH_URL = `${BASE_URL}/connect/token`;
export const REVOKE_URL = `${BASE_URL}/connect/revocation`;